### ISSUE TITLE
Motor control needs some improvement

### ISSUE THREAD

**Issue by jraivio** [TampereTC/IOT-Ralli-2016#5]
In current setup set motor power value is not so logical.
The H-driver bridge value range is 0-255. Meaning in  PWM signal value in Ena(A/B) pins in L298N unit.
However in practice the value range is 100-255.

Proposal: scale the motor power value between 0-100 % and allow different values per motor to control the device. -> Updates are needed in the motor control interfaces and functions

**Comment by jraivio** [comment]
Control has improved: Changes are in code and instructions in the wiki part

**Comment by jasalonen** [comment]
Isn't this fixed now? If so, let's close this.

**Comment by jraivio** [comment]
Yes no it works better. Closed
